baseURL = "http://blog.stuartzahn.net"
languageCode = "en-us"
title = "Blog"
theme = "basics-mod"
SectionPagesMenu = "main"
PygmentsCodeFences = true
PygmentsStyle = "friendly"

[taxonomies]
  tag = "tags"
  thought = "thoughts"
  talk = "talks"
  book = "books"
  howto = "howto"

[params]
    author = "Stuart Zahn"
    authorUrl = "http://stuartzahn.net"
    github = "szahn"
    linkedin = "stuartzahn"


[menu]

    [[menu.main]]
    identifier = "thought"
    name       = "Thoughts"
    url        = "/thought"
    weight     = 3

    [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"
    weight     = 4

    [[menu.main]]
    identifier = "quote"
    name       = "Quotes"
    url        = "/quotes"
    weight     = 6